// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.906

package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/pocketbase/pocketbase/core"

func SearchPage(posts []*core.Record) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = Posts(posts).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Layout("The Feed", "search", LayoutOptions{
			Description: "Prepare the trough, it's time for slop",
			Meta: []MetaTags{
				{Name: "description", Content: "A collection of software, drawings and other useless nonsense."},
				{Name: "keywords", Content: "blog, web development, art, comics, character art, sveltekit, golang, programming, tech, krugg, krug, dngn, draw_dngn, draw dngn, instagram, github"},
				{Name: "author", Content: "krugg.dev"},
				{Name: "robots", Content: "index, follow"},
				{Name: "theme-color", Content: "#000000"},
			},
			Properties: []OGProperty{
				{Property: "og:title", Content: "The Feed - krugg.dev"},
				{Property: "og:description", Content: "A collection of software, drawings and other useless nonsense."},
				{Property: "og:type", Content: "website"},
				{Property: "og:url", Content: "https://krugg.dev"},
				{Property: "og:image", Content: "https://krugg.dev/assets/images/og-home.jpg"},
				{Property: "og:image:width", Content: "1200"},
				{Property: "og:image:height", Content: "630"},
				{Property: "og:site_name", Content: "krugg.dev"},
				{Property: "twitter:card", Content: "summary_large_image"},
				{Property: "twitter:title", Content: "The Feed - krugg.dev"},
				{Property: "twitter:description", Content: "A collection of software, drawings and other useless nonsense."},
				{Property: "twitter:image", Content: "https://krugg.dev/assets/images/twitter-feed-card.png"},
			},
		}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
