// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package queries

import (
	"database/sql"
	"time"
)

type Collection struct {
	ID                          string        `json:"id"`
	Title                       string        `json:"title"`
	Slug                        string        `json:"slug"`
	Description                 string        `json:"description"`
	CollectionDescriptionPostID *string       `json:"collection_description_post_id"`
	ClickedCount                sql.NullInt64 `json:"clicked_count"`
	Created                     sql.NullTime  `json:"created"`
}

type CollectionPost struct {
	ID           string        `json:"id"`
	CollectionID string        `json:"collection_id"`
	PostID       string        `json:"post_id"`
	Order        sql.NullInt64 `json:"order"`
	Created      sql.NullTime  `json:"created"`
}

type Context struct {
	ID                       string       `json:"id"`
	Title                    string       `json:"title"`
	Description              string       `json:"description"`
	ContextDescriptionPostID *string      `json:"context_description_post_id"`
	Created                  sql.NullTime `json:"created"`
}

type ContextPost struct {
	ID        string       `json:"id"`
	PostID    string       `json:"post_id"`
	ContextID string       `json:"context_id"`
	Created   sql.NullTime `json:"created"`
}

type CrosspostJob struct {
	ID       string       `json:"id"`
	Platform string       `json:"platform"`
	PostID   string       `json:"post_id"`
	Created  sql.NullTime `json:"created"`
}

type InstagramDetail struct {
	ID             string       `json:"id"`
	AccountName    string       `json:"account_name"`
	AccessKey      string       `json:"access_key"`
	AccountID      string       `json:"account_id"`
	HasThreadsLink bool         `json:"has_threads_link"`
	Created        sql.NullTime `json:"created"`
}

type InstagramPost struct {
	ID           string         `json:"id"`
	PostID       string         `json:"post_id"`
	InstagramUrl sql.NullString `json:"instagram_url"`
	LastSynced   *time.Time     `json:"last_synced"`
	Created      sql.NullTime   `json:"created"`
}

type Job struct {
	ID            string         `json:"id"`
	JobName       string         `json:"job_name"`
	Status        string         `json:"status"`
	ResultMessage sql.NullString `json:"result_message"`
	Completed     *time.Time     `json:"completed"`
	Created       sql.NullTime   `json:"created"`
}

type Link struct {
	ID              string         `json:"id"`
	Title           sql.NullString `json:"title"`
	IsLocalHref     sql.NullBool   `json:"is_local_href"`
	Href            sql.NullString `json:"href"`
	ImageUrl        sql.NullString `json:"image_url"`
	FindOutMoreHref sql.NullString `json:"find_out_more_href"`
	ClickCount      sql.NullInt64  `json:"click_count"`
	IsVisible       sql.NullBool   `json:"is_visible"`
	Order           sql.NullInt64  `json:"order"`
	Created         sql.NullTime   `json:"created"`
}

type Post struct {
	ID        string         `json:"id"`
	Type      sql.NullString `json:"type"`
	Visible   sql.NullBool   `json:"visible"`
	Title     string         `json:"title"`
	Subtitle  sql.NullString `json:"subtitle"`
	Content   string         `json:"content"`
	Slug      string         `json:"slug"`
	Permalink string         `json:"permalink"`
	Created   sql.NullTime   `json:"created"`
}

type PostTag struct {
	ID      string       `json:"id"`
	PostID  string       `json:"post_id"`
	TagID   string       `json:"tag_id"`
	Created sql.NullTime `json:"created"`
}

type Tag struct {
	ID            string        `json:"id"`
	Title         string        `json:"title"`
	SearchedCount sql.NullInt64 `json:"searched_count"`
	Created       sql.NullTime  `json:"created"`
}

type ThreadsPost struct {
	ID         string       `json:"id"`
	PostID     string       `json:"post_id"`
	LastSynced *time.Time   `json:"last_synced"`
	Created    sql.NullTime `json:"created"`
}
