// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package queries

import (
	"context"
	"database/sql"
)

type Querier interface {
	AddPostToCollection(ctx context.Context, arg AddPostToCollectionParams) (CollectionPost, error)
	AddPostToContext(ctx context.Context, arg AddPostToContextParams) (ContextPost, error)
	AddTagToPost(ctx context.Context, arg AddTagToPostParams) (PostTag, error)
	CountPosts(ctx context.Context, visible sql.NullBool) (int64, error)
	CountPostsByType(ctx context.Context, arg CountPostsByTypeParams) (int64, error)
	CreateCollection(ctx context.Context, arg CreateCollectionParams) (Collection, error)
	CreateContext(ctx context.Context, arg CreateContextParams) (Context, error)
	// Crosspost Jobs
	CreateCrosspostJob(ctx context.Context, arg CreateCrosspostJobParams) (CrosspostJob, error)
	CreateJob(ctx context.Context, arg CreateJobParams) (Job, error)
	CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error)
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error)
	DeleteCollection(ctx context.Context, id string) error
	DeleteContext(ctx context.Context, id string) error
	DeleteLink(ctx context.Context, id string) error
	DeletePost(ctx context.Context, id string) error
	DeleteTag(ctx context.Context, id string) error
	GetCollection(ctx context.Context, id string) (Collection, error)
	GetCollectionBySlug(ctx context.Context, slug string) (Collection, error)
	GetCollectionPosts(ctx context.Context, collectionID string) ([]Post, error)
	GetContext(ctx context.Context, id string) (Context, error)
	GetContextByTitle(ctx context.Context, title string) (Context, error)
	GetContextPosts(ctx context.Context, contextID string) ([]Post, error)
	GetCrosspostJobsByPlatform(ctx context.Context, arg GetCrosspostJobsByPlatformParams) ([]CrosspostJob, error)
	GetCrosspostJobsByPost(ctx context.Context, postID string) ([]CrosspostJob, error)
	GetJob(ctx context.Context, id string) (Job, error)
	GetJobsByName(ctx context.Context, arg GetJobsByNameParams) ([]Job, error)
	GetLink(ctx context.Context, id string) (Link, error)
	GetPopularTags(ctx context.Context, limit int64) ([]Tag, error)
	GetPost(ctx context.Context, id string) (Post, error)
	GetPostByPermalink(ctx context.Context, permalink string) (Post, error)
	GetPostBySlug(ctx context.Context, slug string) (Post, error)
	GetPostTags(ctx context.Context, postID string) ([]Tag, error)
	GetRecentPosts(ctx context.Context, limit int64) ([]Post, error)
	GetTag(ctx context.Context, id string) (Tag, error)
	GetTagByTitle(ctx context.Context, title string) (Tag, error)
	GetTagPosts(ctx context.Context, tagID string) ([]Post, error)
	IncrementCollectionClicks(ctx context.Context, id string) error
	IncrementLinkClicks(ctx context.Context, id string) error
	IncrementTagSearchCount(ctx context.Context, id string) error
	ListAllLinks(ctx context.Context, arg ListAllLinksParams) ([]Link, error)
	ListCollections(ctx context.Context, arg ListCollectionsParams) ([]Collection, error)
	ListContexts(ctx context.Context, arg ListContextsParams) ([]Context, error)
	ListJobs(ctx context.Context, arg ListJobsParams) ([]Job, error)
	ListJobsByStatus(ctx context.Context, arg ListJobsByStatusParams) ([]Job, error)
	ListPosts(ctx context.Context, arg ListPostsParams) ([]Post, error)
	ListPostsByType(ctx context.Context, arg ListPostsByTypeParams) ([]Post, error)
	ListTags(ctx context.Context, arg ListTagsParams) ([]Tag, error)
	ListVisibleLinks(ctx context.Context) ([]Link, error)
	RemovePostFromCollection(ctx context.Context, arg RemovePostFromCollectionParams) error
	RemovePostFromContext(ctx context.Context, arg RemovePostFromContextParams) error
	RemoveTagFromPost(ctx context.Context, arg RemoveTagFromPostParams) error
	SearchCollections(ctx context.Context, arg SearchCollectionsParams) ([]Collection, error)
	SearchContexts(ctx context.Context, arg SearchContextsParams) ([]Context, error)
	SearchPosts(ctx context.Context, arg SearchPostsParams) ([]Post, error)
	SearchTags(ctx context.Context, arg SearchTagsParams) ([]Tag, error)
	UpdateCollection(ctx context.Context, arg UpdateCollectionParams) (Collection, error)
	UpdateContext(ctx context.Context, arg UpdateContextParams) (Context, error)
	UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) (Job, error)
	UpdateLink(ctx context.Context, arg UpdateLinkParams) (Link, error)
	UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error)
	UpdatePostOrderInCollection(ctx context.Context, arg UpdatePostOrderInCollectionParams) error
	UpdateTag(ctx context.Context, arg UpdateTagParams) (Tag, error)
}

var _ Querier = (*Queries)(nil)
